### PR TITLE
Add nomissingbuildids, noautoreq, noautoprov flags

### PR DESCRIPTION
**Pull request by insilications**
New useful controlling flags for options.conf that helps to build certain packages

### CODE REVIEW

**Comment by fenrus75** [comment]
I'm not immediately a fan...
these flags often end up with broken packages, and are likely an indication of something much bigger going on where the package is really not good for autospec.

maybe examples of actual things can convince me, but I'm not a fan on making broken packages....

**Comment by insilications** [comment]
I created an autospec'd package for the latest installed CUDA version in order to populate my local repo and build some machine learning packages with mock. rpmbuild fails for CUDA (missing build ids and creates unnecessary dependency requirements when it looks into some of the shared libraries provided by CUDA, such as Qt 5.9). You are probably right about enabling the build of broken packages. I thought this could help people in some other use cases.

**Comment by fenrus75** [comment]
I'm not too worried about the build-id thing, we even had that by default for some time
(it just means you do not get any debug info but well.. so be it)

the requirements is what worries me..... that's directly leading to broken packages.

if you have a false requirement that is truely false, a workaround is to make a dummy package in your repo that just Provides: that one thing.

the autoreqprov is for ALL dependencies, too big a hammer normally compared to a very narrow 1 or 2 unfortunate ones.

**Comment by fenrus75** [comment]
I can imagine a "fakeprovides" file in autospec where any truely false requirement can just be Provided: directly.... that's much more surgical than turning off all requires

**Comment by insilications** [comment]
> if you have a false requirement that is truely false, a workaround is to make a dummy package in your repo that just Provides: that one thing.

> I can imagine a "fakeprovides" file in autospec where any truely false requirement can just be Provided: directly.... that's much more surgical than turning off all requires

Yes, makes sense. This approach is much more safe and precise.

**Pull request closed without merging**
