### PR TITLE
Add support for AVX2 and AVX512 build for build_pattern=make

### PR DESCRIPTION
**Pull request by thiagomacieira**
Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>

### CODE REVIEW

**Comment by VictorRodriguez** [comment]
Wasnt this already on autospec? weird I had the idea that use_avx2 = true in options.conf was doing this

**Comment by thiagomacieira** [comment]
No, it just looked like it did: the `write_prep()` and `write_make_install()` parts did create a copy of the sources and ran `make install` there, so it did build twice. But nowhere did it set CFLAGS, so you actually had two copies of the same baseline build.

**Comment by VictorRodriguez** [comment]
I did the following experiment and it generates this : 
https://hastebin.com/neyovemoce.diff

Maybe I am not getting the point of the patch

**Comment by VictorRodriguez** [comment]
+export CFLAGS="$CFLAGS -m64 -march=haswell"
+export CXXFLAGS="$CXXFLAGS -m64 -march=haswell"
+export LDFLAGS="$LDFLAGS -m64 -march=haswell"
+%reconfigure --disable-static
+make  %{?_smp_mflags}
+popd
+unset PKG_CONFIG_PATH
+pushd ../buildavx512/
+export CFLAGS="$CFLAGS -m64 -march=skylake-avx512 -mprefer-vector-width=512"
+export CXXFLAGS="$CXXFLAGS -m64 -march=skylake-avx512 -mprefer-vector-width=512"
+export LDFLAGS="$LDFLAGS -m64 -march=skylake-avx512"

**Comment by bryteise** [comment]
@VictorRodriguez seeing that you have a %reconfigure macro there so it isn't the make build pattern.

**Comment by VictorRodriguez** [comment]
LOL sorry for the confusion :) +1 then

**Pull request merged**
