### PR TITLE
autospec: openmpi support

### PR DESCRIPTION
**Pull request by jurobystricky**
Initial support for concurrent serial and parallel build.
Serial build remains unaffected.

Created new setting in "options.conf" openmpi = false|true (false is default)

Support for additional build controlling files (equivalent to serial builds):
   "configure_openmpi"
   "cmake_args_openmpi"

Creation of additional packages:
   foo-openmpi
   foo-openmpi-dev
   foo-openmpi-staticdev

No support for AVX at present. The only build pattern fully supported is
"configure".

Signed-off-by: Juro Bystricky <juro.bystricky@intel.com>

### CODE REVIEW

**Comment by jurobystricky** [comment]
D'oh! I'll fix the Travis errors in a new PR.

**Comment by jurobystricky** [comment]
I believe "cmake" pattern will also build/install correctly as-is if cmake called with 
<pre>
-DCMAKE_INSTALL_BINDIR=/usr/lib64/openmpi/bin
-DCMAKE_INSTALL_LIBDIR=/usr/lib64/openmpi/lib
-DCMAKE_INSTALL_INCLUDEDIR=/usr/include/openmpi-x86-64 
</pre>
I will verify this. If so, those definitions should be generated by autospec (or RPM/macro)

**Comment by bryteise** [comment]
Hey sorry I didn't get to this one sooner. Would you mind rebasing and I'll take a look at it. Overall it seems pretty reasonable though.

**Comment by jurobystricky** [comment]
I have some additional changes. I keep the latest code in my fork of the repo, currently rebased. It is probably better to have look there before I create a new PR, as it is still a bit of a moving target. I also rely on some new macros in clr-rpm-config (again, in my fork): %configure_openmpi, %cmake_openmpi. I successfully autospeced/built some packages, but there are some rough edges. Notably the absence of AVX support.

https://github.com/jurobystricky/autospec
https://github.com/jurobystricky/clr-rpm-config

**Comment by jurobystricky** [comment]
The latest forced-pushed PR should be more complete and properly rebased.

**Pull request closed without merging**
