### PR TITLE
Add support for generic sha256 verification

### PR DESCRIPTION
**Pull request by thiagomacieira**
So long as get_hash_url returns a URL, we'll try to use it

Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>

### CODE REVIEW

**Comment by phmccarty** [comment]
I would like to get my PR integrated (hopefully by tomorrow) before tackling this issue.

**Comment by phmccarty** [comment]
I don't see any obvious problems with this approach though.

**Comment by thiagomacieira** [comment]
We can wait. I'll have a few more autospecs along the day and will find/fix issues with this.

**Comment by bryteise** [comment]
Okay, now we can take another look at this one.

**Comment by phmccarty** [comment]
@thiagomacieira So, I think the intent here is for `GenericDownloadVerifier` to first construct several hash URLs and try to download each in turn. Right now, it is still using `get_hash_url`, which only understands how to handle download.gnome.org and download.qt.io domains.

I can take over the work on this if you prefer.

**Pull request closed without merging**
