### PR TITLE
add subdir for autogen

### PR DESCRIPTION
**Pull request by K1ngfish3r**
fixes https://github.com/clearlinux/autospec/issues/855

### CODE REVIEW

**Comment by bryteise** [comment]
flake didn't like you moving that git import

**Comment by K1ngfish3r** [comment]
buh why? I used `isort`

**Comment by bryteise** [comment]
Some difference in setting perhaps? isort on clear linux gives me the same output as the current import layout.

**Comment by K1ngfish3r** [comment]
fresh install btw
image

**Pull request merged**
