### PR TITLE
Use external tar instead of python's tarfile.

### PR DESCRIPTION
**Pull request by busykai**
tarfile module in python has limited support for compression.
Particularly, it does not support lzip (.lz). Since we're using tar to
ultimately extract the tarball, use it, instead of python's module, to
detect the contents too.

### CODE REVIEW

**Comment by bryteise** [comment]
Ugh we just got subprocess out of that. I think ed is literally the only package using lzip at this point and the repo provides differently compressed tar files. Generally people use xz for lzma instead anyway so I am not particularly worried about this.

**Comment by busykai** [comment]
OK. Withdrawn. I dislike relying on an incompatible implementation though, but I do understand potential problems with parsing a command output.

**Comment by phmccarty** [comment]
@bryteise What repo are you referring to where differently compressed tars are available for `ed`? There's a new release that I'm trying to update to...

**Comment by bryteise** [comment]
https://github.com/happy5214/gnu-ed/releases though obviously these aren't the release tars so maybe they won't work.

**Comment by bryteise** [comment]
Might be able to send an email to the upstream mailing list and ask nicely though for non-lzip content.

**Pull request closed without merging**
