### PR TITLE
Add support for [un]installation scriptlets

### PR DESCRIPTION
**Pull request by MarioCarrilloA**
These commits add support for pre/post/preun/postun scriptlets.
This in order to control the RPM package [un]installation.

The serie of commands can be established in a file according to the
functionality, this relation is described below:

| Scriptlet | File name      |
| --------- | -------------- |
| %pre      | pre_install    |
| %preun    | pre_uninstall  |
| %post     | post_install   |
| %postun   | post_uninstall |

### CODE REVIEW

**Comment by phmccarty** [comment]
On Clear Linux, there are virtually no packages that define scriptlets, and this is intentional. Is this feature intended to support non-Clear Linux use cases?

**Comment by MarioCarrilloA** [comment]
Hi @phmccarty , yeah, you are right, stateless feature defines that behavior, however the objective of this PR is to use `autospec` for non-Clear systems. The scriptlets/commands will be added  inside the SPEC file just in the case the helper files (pre_install, post_install etc) exist, this is in order to not break the current stateless packages, what do you think?

**Comment by fenrus75** [comment]
If we end up going this way, we should allow a site configuration (in
common/ whatever) that bans these and will not let them be picked up, so
that we can enforce our no-%post policy centrally for Clear Linux

**Comment by fenrus75** [comment]
And it's not because of stateless. We have this policy because we do not
use RPMs to distribute software (we use swupd), only to build software.
%post usage would break many of the assumptions and invariants we have for
swupd....
swupd has it's own mechanisms to do things post install.

**Comment by bryteise** [comment]
Ah yes I expected a stateless field in options.conf to be added as part of this change that would then use the files if statless was turned off.

**Comment by MarioCarrilloA** [comment]
Thanks @bryteise , expect a new version :)

**Comment by fenrus75** [comment]
I'd not want this in per package options.conf
we need a central off switch in the overall distro configuration scripts
that autospec reads.

%post is not allowed in CL and we need to avoid accidents, not just for our
users, but also for people who mixes
(so it needs to live in common/)

**Comment by mrkz** [comment]
uh, probably not in `options.conf` but in `autospec.conf` instead

**Comment by matthewrsj** [comment]
@MarioCarrilloA are you still working on a new version of this?

**Comment by matthewrsj** [comment]
@MarioCarrilloA are you still working on this or should the PR be closed?

**Comment by MarioCarrilloA** [comment]
Hi @matthewrsj, I am not working on this for the moment, could be better to close it, thanks

**Comment by matthewrsj** [comment]
Ok, thanks

**Pull request closed without merging**
