### PR TITLE
Removed `infile` features

### PR DESCRIPTION
**Pull request by lebensterben**
There are multiple issues regarding `infile` support.

Notably,
- It doesn't support some basic syntax of `BitBake`.
- It doesn't fully comply to `BitBake`'s conventions.
- The differences from `BitBake` is not well-documented.

Since this is never used, I propose to remove this functionality entirely.

https://github.com/clearlinux/autospec/issues/645
https://github.com/clearlinux/autospec/issues/646

### CODE REVIEW

**Comment by phmccarty** [comment]
@lebensterben I am okay with removing these features, but I would prefer not to see all of the code style changes interleaved in the same commit... Did your editor make the style changes automatically?

If you would like to make some changes to code style, make a separate commit (with rationale in the commit description if necessary), and make sure that the changes apply to the entire code base. Or you can omit the style changes from this PR if you prefer.

**Comment by lebensterben** [comment]
Yeah. emacs applied reformatted some files according and reordered imports.

**Comment by lebensterben** [comment]
It's done now.
BTW, would you add a `.editorconfig` or `.flake8` file to the root, so that modern editors can use your per-project style settings?

**Comment by phmccarty** [comment]
The flake8 config already enforced by Github Actions. You can run the checks locally by running `make check`. The behavior is controlled via the toplevel `setup.cfg`.

I like the idea of adding a `.editorconfig`, since it can cover basic style issues. Opened an issue for that: #648

**Comment by phmccarty** [comment]
@lebensterben It looks like all test files under `tests/testfiles/bb/` can be removed as well? Can you check that?

Otherwise, changes look good to me.

**Comment by lebensterben** [comment]
@phmccarty I removed them (`tests/testfiles/bb`) in the new commit.

**Pull request merged**
