### PR TITLE
Add travis config

### PR DESCRIPTION
**Pull request by bryteise**

### CODE REVIEW

**Comment by matthewrsj** [comment]
-1, using this config there are several errors.

Make sure to pip install the requirements for toml and pycurl

**Comment by matthewrsj** [comment]
@bryteise beta feature on travis CI lets you create a fake commit internal to travis to test your travis configuration. The feature is under "More Options" -> "Trigger Build".

**Comment by bryteise** [comment]
@matthewrsj Oh that's nifty, I'll have to poke at that next time.

**Comment by matthewrsj** [comment]
yay, flake8 is working, but I don't like that the pkg_integrity tests fail in travis and not locally and that `make unittests` doesn't report a failure when that happens.

I don't really like that pkg_integrity tests use network anyways. That should be mocked away. Maybe now is the time?

**Comment by matthewrsj** [comment]
Hmm, I'm not convinced this is just a networking thing with the pkg_integrity tests. In fact, we know networking is working in the travis environment. I'm seeing 4 test failures for pkg_integrity locally anyway.

**Comment by matthewrsj** [comment]
+1, I'd like to get those pkg_integrity tests fixed for travis soon (#7)

**Pull request merged**
