### PR TITLE
Make sub-packages require/provide exact versions

### PR DESCRIPTION
**Pull request by thiagomacieira**
I'm seeing at least one package that weirdly causes an old version to
get installed by dnf, causing file conflicts later.

### CODE REVIEW

**Comment by bryteise** [comment]
This would be handy for testing purposes.

**Comment by thiagomacieira** [comment]
What would be handy? Installing different versions? Or forcing the version?

**Comment by bryteise** [comment]
Your change here for forcing the version. We sometimes run into problems with testing where dependencies are satisfied by an earlier version of a subpackage that isn't provided in the new release. This would break the link on that dependency in some cases making a more obvious failure rather than sneaking in a different version of a subpackage that won't be available when making a release.

**Comment by bryteise** [comment]
I'd take it, thanks!

**Pull request merged**
