### PR TITLE
Add autospec.py as a script

### PR DESCRIPTION
**Pull request by bensallen**
Add autospec/autospec.py as a script so setuptools installs it into /usr/bin.

### CODE REVIEW

**Comment by matthewrsj** [comment]
This doesn't work for me, it immediately fails to `import build`

```

**Comment by bensallen** [comment]
Hmm works for me:

```
$ git show | head -n1
commit b81da703805f0e8439fb261dcb466afc7071a858
$ python3 setup.py build
running build
running build_py
running egg_info
writing autospec.egg-info/PKG-INFO
writing dependency_links to autospec.egg-info/dependency_links.txt
writing top-level names to autospec.egg-info/top_level.txt
reading manifest template 'MANIFEST.in'
writing manifest file 'autospec.egg-info/SOURCES.txt'
running build_scripts
```

**Comment by matthewrsj** [comment]
Sorry, `python3 setup.py build` works for me, but the `autospec.py` script in `/usr/bin` is not runnable due to the traceback I posted above.

**Comment by bensallen** [comment]
Hrm... confirmed. Will look into this more.

**Comment by bensallen** [comment]
Closed and moved work to #21.

**Pull request closed without merging**
